version: 0.2
phases:
 install:
   commands:
     - echo "Build Starting..."
 build:
   commands:
     - env
     - phpenv global $PHP_73_VERSION
     - composer install --no-progress --no-suggest
     - pwd
     - ls -ltr

 post_build:
   commands:
     - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  name: test-php-cb-$(date +%Y-%m-%d).zip
